### ISSUE TITLE
Number of speakers in output segmentation exceeds maxNrSpeakers

### ISSUE THREAD

**Issue by davidwesby** [josepatino/pyBK#3]
I am trying to diarise an audio clip in which two people are speaking. In my configuration file, I have set `maxNrSpeakers = 2`. However, in the output segmentation, there are nine speakers: `speaker1` to `speaker9`. Is this really the intended behaviour?

**Comment by josepatino** [comment]
Hello David,

I am sorry it took me this long to get back to you about this. The truth is that if you read the config file well you will see the maximum number of speakers choice was meant to be applied only when using the spectral clustering algorithm. The behavior you report is normal if it was the the elbow criterion that you used to determine the best clustering choice. However, I just pushed a modification that makes that parameter affect the elbow criterion now too, I hope it could still be useful for you.

Best regards,
Jose
